= Azure Entra ID (AD)
Nick Hardiman <nhardima@redhat.com>
:source-highlighter: highlight.js
:revdate: 10-12-2023

== links 

https://learn.microsoft.com/en-us/entra/


== learn about Azure

https://www.linkedin.com/learning/microsoft-azure-fundamentals-az-900-cert-prep-1-cloud-concepts-by-microsoft-press/learning-objectives

https://www.pluralsight.com/paths/az-900-microsoft-azure-fundamentals

az900
https://learn.microsoft.com/en-us/credentials/certifications/exams/az-900/

Study guide for Exam AZ-900: Microsoft Azure Fundamentals
and link to exam sandbox 
https://learn.microsoft.com/en-gb/credentials/certifications/resources/study-guides/az-900


=== learning paths 

https://learn.microsoft.com/en-us/credentials/certifications/exams/az-900/

* Microsoft Azure Fundamentals: Describe cloud concepts
** Describe cloud computing
** Describe the benefits of using cloud services
** Describe cloud service types
* Microsoft Azure Fundamentals: Describe Azure architecture and services
* Microsoft Azure Fundamentals: Describe Azure management and governance


=== certification

Exam AZ-900: Microsoft Azure Fundamentals
£69 GBP
https://learn.microsoft.com/en-us/credentials/certifications/exams/az-900/

Skills measured
The English language version of this exam was updated on July 31, 2023. Review the study guide linked in the preceding “Tip” box for details about the skills measured and latest changes.

* Describe cloud concepts (25–30%)
* Describe Azure architecture and services (35–40%)
* Describe Azure management and governance (30–35%)

exam sandbox 
is 10 simple questions to demonstrate how the exam works. 
https://learn.microsoft.com/en-gb/credentials/certifications/resources/study-guides/az-900

exam features 
https://aka.ms/ExamFeatures
https://learn.microsoft.com/en-gb/credentials/support/exam-duration-exam-experience

exam accomodatons 
https://aka.ms/ExamAccomodations

certifications 
https://aka.ms/MicrosoftCertifications


== learn about azure AD / azure entra ID

https://learn.microsoft.com/en-us/entra/
