= create an Ansible collection
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 19-11-2023

== parts of a new collection 

Build a simple Ansible collection.

The Ansible developer site has a guide to 
https://docs.ansible.com/ansible/latest/dev_guide/developing_collections.html[developing collections].

includes 

* role 
* playbook


== /home/nick/my-ansible/collections/ansible_collections/

The default area for storing Ansible collections is _~/.ansible/collections/ansible_collections/_. 
Directory .ansible is https://en.wikipedia.org/wiki/Hidden_file_and_hidden_directory[hidden], like all Linux dotfiles.
For me, the "~" tilde character expands to make the full path /home/nick/my-ansible/collections/ansible_collections/.

The area I make for creating my own collections is _~/my-ansible/collections/ansible_collections/_. 
This new ansible directory is not hidden  (_my-ansible_, not _.ansible_).
This directory is not part of the collections path and is not going to be found by a playbook, so I must add config to tell Ansible where to look. 

== create an area for collection development

Don't start with an empty git repo. 
ansible-galaxy collection init will trash it. 

Now you see it ...

[source,shell]
----
[nick@dev ~]$ cd /home/nick/my-ansible/collections/ansible_collections/mynamespace/mycode/
[nick@dev mycode]$ ls
README.md
[nick@dev mycode]$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
[nick@dev mycode]$ 
----

== create a collection development skeleton

Build a new collection framework.

The _--force_ option is required because the directory already exists, and the _ansible-galaxy_ command doesn't want to risk trashing work.	

Using --force trashes directory content. 

[source,shell]
----
[nick@dev mycode]$ cd /home/nick/my-ansible/collections/ansible_collections/
[nick@dev ansible_collections]$ ansible-galaxy collection init mynamespace.mycode --force
- Collection mynamespace.mycode was created successfully
[nick@dev ansible_collections]$ 
[nick@dev ansible_collections]$ cd mynamespace/mycode
[nick@dev mycode]$ 
[nick@dev mycode]$ ls
docs  galaxy.yml  meta  plugins  README.md  roles
[nick@dev mycode]$ 
[nick@dev mycode]$ cat README.md 
# Ansible Collection - mynamespace.mycode

Documentation for the collection.
[nick@dev mycode]$ 
----

...Now you don't.

----
[nick@dev mycode]$ git status
fatal: not a git repository (or any of the parent directories): .git
[nick@dev mycode]$
----


== store the skeleton using git

Create a new local git repository.
Set it up to sync to the remote Gitlab repository. 

[source,shell]
----
[nick@dev ~]$ cd /home/nick/my-ansible/collections/ansible_collections/mynamespace/mycode/
[nick@dev mycode]$ git init .
Initialized empty Git repository in /home/nick/my-ansible/collections/ansible_collections/mynamespace/mycode/.git/
[nick@dev mycode]$ 
[nick@dev mycode]$ git remote add origin "https://nick:Password;1@git.source.example.com/my-ansible/ansible-collection-mycode.git"
[nick@dev mycode]$ 
[nick@dev mycode]$ mv README.md /var/tmp/
[nick@dev mycode]$ git pull origin main
From https://git.source.example.com/my-ansible/ansible-collection-mycode
 * branch            main       -> FETCH_HEAD
[nick@dev mycode]$ 
[nick@dev mycode]$ mv /var/tmp/README.md .
[nick@dev mycode]$ 
[nick@dev mycode]$ git status
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   README.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	galaxy.yml
	meta/
	plugins/

no changes added to commit (use "git add" and/or "git commit -a")
[nick@dev mycode]$ 
[nick@dev mycode]$ git add .
[nick@dev mycode]$ 
[nick@dev mycode]$ git commit -m initial
[main 7337d53] initial
 4 files changed, 154 insertions(+), 91 deletions(-)
 create mode 100644 galaxy.yml
 create mode 100644 meta/runtime.yml
 create mode 100644 plugins/README.md
[nick@dev mycode]$ 
[nick@dev mycode]$ git push --set-upstream origin main
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (8/8), 2.77 KiB | 2.77 MiB/s, done.
Total 8 (delta 0), reused 0 (delta 0), pack-reused 0
To https://git.source.example.com/my-ansible/ansible-collection-mycode.git
   a0ae499..7337d53  main -> main
branch 'main' set up to track 'origin/main'.
[nick@dev mycode]$ 
----

Check.

[source,shell]
----
git status
git branch -v
git remote -v
ls
----


== add a role development skeleton

Add a test role to the collection.

[source,shell]
----
cd /home/nick/my-ansible/collections/ansible_collections/mynamespace/mycode/roles/
ansible-galaxy role init my_role
----

Add a task to the role.
[source,shell]
----
cd my_role/tasks
echo -e "- name: Say hello\n  debug:\n    msg: Hello\n" >> main.yml 
----


== add a playbook

Add a test playbook to the collection.

[source,shell]
----
cd /home/nick/my-ansible/collections/ansible_collections/mynamespace/mycode/
mkdir playbooks
echo '
---
- name: Say hello
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - name: mynamespace.mycode.my_role
' >  playbooks/test.yml
----


== tell Ansible about the new collection directory

Change the collections search path.

Check before. 

[source,shell]
----
[nick@dev ~]$ ansible --version | grep collection
  ansible collection location = /home/nick/.my-ansible/collections:/usr/share/my-ansible/collections
[nick@dev ~]$ 
----

Add the new collections path to the end of this list. 
Use /home/nick/my-ansible/collections, not /home/nick/my-ansible/collections/ansible_collections/mynamespace/mycode/.

[source,shell]
----
[nick@dev ~]$ export ANSIBLE_COLLECTIONS_PATH=/home/nick/.my-ansible/collections:/usr/share/my-ansible/collections:/home/nick/my-ansible/collections
[nick@dev ~]$ 
----

Check after. 

[source,shell]
----
[nick@dev ~]$ ansible --version | grep collection
  ansible collection location = /home/nick/.my-ansible/collections:/usr/share/my-ansible/collections:/home/nick/my-ansible/collections
[nick@dev ~]$ 
----

You can also change the search path value temporarily.
This version changes the search path only while the ansible-playbook command executes. 

[source,shell]
----
ANSIBLE_COLLECTIONS_PATH=/home/nick/my-ansible/collections \
  ansible-playbook mynamespace.mycode.test
----


== test the collection

Test.
Start in any directory.

[source,shell]
----
[nick@dev tasks]$ cd
[nick@dev ~]$ 
[nick@dev ~]$ ansible-playbook mynamespace.mycode.test
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does
not match 'all'
[WARNING]: running playbook inside collection mynamespace.mycode

PLAY [Say hello] *******************************************************************************************

TASK [mynamespace.mycode.my_role : Say hello] ******************************************************
ok: [localhost] => {
    "msg": "Hello"
}

PLAY RECAP *************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   

[nick@dev ~]$
----

Running the ansible-playbook command in a directory without an inventory file causes a _provided hosts list is empty_ warning to appear.
Specify a directory on the command line to get rid of this warning. 

[source,shell]
----
[nick@dev ~]$ ansible-playbook -i localhost, mynamespace.mycode.test
[WARNING]: running playbook inside collection mynamespace.mycode

PLAY [Say hello] 
...
----

== commit to the git repository

Check

[source,shell]
----
[nick@dev ~]$ cd /home/nick/my-ansible/collections/ansible_collections/mynamespace/mycode/
[nick@dev mycode]$ 
[nick@dev mycode]$ git status
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   README.md

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	galaxy.yml
	meta/
	playbooks/
	plugins/
	roles/

no changes added to commit (use "git add" and/or "git commit -a")
[nick@dev mycode]$ 
----

[source,shell]
----
[nick@dev mycode]$ git add .
[nick@dev mycode]$ 
[nick@dev mycode]$ git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   README.md
	new file:   galaxy.yml
	new file:   meta/runtime.yml
	new file:   playbooks/test.yml
	new file:   plugins/README.md
	new file:   roles/my_role/README.md
	new file:   roles/my_role/defaults/main.yml
	new file:   roles/my_role/handlers/main.yml
	new file:   roles/my_role/meta/main.yml
	new file:   roles/my_role/tasks/main.yml
	new file:   roles/my_role/tests/inventory
	new file:   roles/my_role/tests/test.yml
	new file:   roles/my_role/vars/main.yml

[nick@dev mycode]$ 
----

[source,shell]
----
[nick@dev mycode]$ git commit -m 'first role and playbook'
[main 5481e96] first role and playbook
 13 files changed, 272 insertions(+), 91 deletions(-)
 create mode 100644 galaxy.yml
 create mode 100644 meta/runtime.yml
 create mode 100644 playbooks/test.yml
 create mode 100644 plugins/README.md
 create mode 100644 roles/my_role/README.md
 create mode 100644 roles/my_role/defaults/main.yml
 create mode 100644 roles/my_role/handlers/main.yml
 create mode 100644 roles/my_role/meta/main.yml
 create mode 100644 roles/my_role/tasks/main.yml
 create mode 100644 roles/my_role/tests/inventory
 create mode 100644 roles/my_role/tests/test.yml
 create mode 100644 roles/my_role/vars/main.yml
[nick@dev mycode]$ 
----
