= create a Gitlab project using the API
Nick Hardiman 
:source-highlighter: highlight.js
:revdate: 19-12-2023


This works from any machine.

[source,shell]
----
ssh nick@dev.build.example.com
----

== define group values

Define a few values for the new group.

[source,shell]
----
PROJECT_NAME='ansible-collection-mycode'
PROJECT_DESC='My new Ansible collection.'
PROJECT_README='true'
----


== find the "my-ansible" group namespace ID

https://docs.gitlab.com/ee/api/namespaces.html

A https://docs.gitlab.com/ee/user/namespace/index.html[namespace] is Gitlab's collective name for user and group names.
A namespace helps Gitlab users organize their projects.

The namespace ID for ansible is displayed on the web UI at 
https://git.source.example.com/groups/ansible.
This method uses the API, not the web UI.

Search for the ansible group ID.

[source,shell]
----
PAT_API=glpat-862ezbSoy6xY_Po6x-4X
URL="https://git.source.example.com/api/v4/namespaces?search=my-ansible"
curl \
  --silent \
  --verbose \
  --request GET \
  --header "PRIVATE-TOKEN: $PAT_API" \
  "$URL" \
| jq .
----

Run the command. 

The verbose option displays lots of information about the conversation between curl and the Gitlab server.
The last part is the payload - data with the ID in it. 

[source,shell]
----
[nick@dev ~]$ PAT_API=glpat-862ezbSoy6xY_Po6x-4X
...
* Connected to git.source.example.com (192.168.11.7) port 443 (#0)
...
* TLSv1.3 (OUT), TLS handshake, Finished (20):
...
* Server certificate:
*  subject: CN=git.source.example.com
...
* Using HTTP2, server supports multi-use
...
< HTTP/2 200 
< server: nginx
...
[
  {
    "id": 22,
    "name": "My Ansible",
    "path": "my-ansible",
    "kind": "group",
    "full_path": "my-ansible",
    "parent_id": null,
    "avatar_url": null,
    "web_url": "https://git.source.example.com/groups/my-ansible",
    "members_count_with_descendants": 1,
    "root_repository_size": null,
    "projects_count": 0
  }
]
[nick@dev ~]$ 
----

Copy the _id_ value. 

[source,shell]
----
GROUP_ID=22
----


== create a project

https://docs.gitlab.com/ee/api/projects.html#create-project

Use the curl command.

[source,shell]
----
PAT_API=glpat-862ezbSoy6xY_Po6x-4X
GROUP_ID=22
URL="https://git.source.example.com/api/v4/projects/"
curl \
  --silent \
  --verbose \
  --request POST \
  --header "PRIVATE-TOKEN: $PAT_API" \
  --data  "name=$PROJECT_NAME" \
  --data  "description=$PROJECT_DESC" \
  --data  "initialize_with_readme=$PROJECT_README" \
  --data  "namespace_id=$GROUP_ID" \
  --url "$URL" \
| jq .
----


The reply contains a lot of settings. 


[source,shell]
----
[nick@dev ~]$ TOKEN="glpat-LQ89656f6pBYtT6yy4zk"
...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4431  100  4271  100   160   7545    282 --:--:-- --:--:-- --:--:--  7828
{
  "id": 13,
  "description": "My new Ansible collection.",
  "name": "ansible-collection-mycode",
  "name_with_namespace": "My Ansible / ansible-collection-mycode",
  "path": "ansible-collection-mycode",
  "path_with_namespace": "my-ansible/ansible-collection-mycode",

...(another 100 of these)...

  "merge_commit_template": null,
  "squash_commit_template": null,
  "issue_branch_template": null,
  "autoclose_referenced_issues": true
}
[nick@dev ~]$ 
----


This project is now visible in the web UI at https://git.source.example.com/my-ansible/ansible-collection-mycode.



== check your work

The first attribute to appear in the reply is the new project ID. 

[source,shell]
----
PROJECT_ID=13
----
Use the project ID to get information about the project.

[source,shell]
----
PAT_API=glpat-862ezbSoy6xY_Po6x-4X
PROJECT_ID=13
URL="https://git.source.example.com/api/v4/projects/$PROJECT_ID"
curl \
  --silent \
  --verbose \
  --request GET \
  --header "PRIVATE-TOKEN: $PAT_API" \
  "$URL" \
| jq .
----

The reply is a big JSON object that is almost the same as the first reply, when creating the project. 

[source,shell]
----
[nick@dev ~]$ curl --silent  --header "PRIVATE-TOKEN: $TOKEN"   --request GET   "$URL" | jq .
{
  "id": 13,
  "description": "My new Ansible collection.",
  "name": "ansible-collection-mycode",
...
  "permissions": {
    "project_access": null,
    "group_access": {
      "access_level": 50,
      "notification_level": 3
    }
  }
}
[nick@dev ~]$ 
----
